export const CUSTOMERS_GET_LOADING = "CUSTOMERS_GET_LOADING";
export const CUSTOMERS_GET_SUCCESS = "CUSTOMERS_GET_SUCCESS";
export const CUSTOMERS_GET_FAILURE = "CUSTOMERS_GET_FAILURE";

export const CUSTOMER_GET_LOADING = "CUSTOMER_GET_LOADING";
export const CUSTOMER_GET_SUCCESS = "CUSTOMER_GET_SUCCESS";
export const CUSTOMER_GET_FAILURE = "CUSTOMER_GET_FAILURE";

export const CUSTOMER_ADD_LOADING = "CUSTOMER_ADD_LOADING";
export const CUSTOMER_ADD_SUCCESS = "CUSTOMER_ADD_SUCCESS";
export const CUSTOMER_ADD_FAILURE = "CUSTOMER_ADD_FAILURE";

export const CUSTOMER_UPDATE_LOADING = "CUSTOMER_UPDATE_LOADING";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAILURE = "CUSTOMER_UPDATE_FAILURE";

export const CUSTOMER_DELETE_LOADING = "CUSTOMER_DELETE_LOADING";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAILURE = "CUSTOMER_DELETE_FAILURE";